# Generated by Django 6.0.2 on 2026-03-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('projects', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='org.product'),
        ),
    ]
