# Generated by Django 6.0.2 on 2026-03-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_phase_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.stage'),
        ),
    ]
